### PR TITLE
fix: set attributes of http_client_request

### LINKED ISSUE #175: Error in server using eureka discovery in a spring boot app
I'm trying appmap for the first time.

No problem with a remote recording of the http endpoints.

But I have this error when using the javaagent on my service.

```
2023-04-20 17:08:30.343  INFO [prometheus,,] 44579 --- [freshExecutor-0] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error. endpoint=DefaultEndpoint{ serviceUrl='http://localhost:8102/eureka/}, exception=java.lang.NullPointerException stacktrace=com.sun.jersey.api.client.ClientHandlerException: java.lang.NullPointerException
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:196)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:167)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.executeOnNewServer(RedirectingEurekaHttpClient.java:121)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:80)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:120)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.DiscoveryClient.getAndStoreFullRegistry(DiscoveryClient.java:1101)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:1014)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1531)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1498)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at com.appland.appmap.process.hooks.HttpClientRequest.execute(HttpClientRequest.java:27)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173)
```

### PR DESCRIPTION
**Pull request by apotterri**
Make sure message and parameters are set correctly for an http_client_request. Also, make sure a response without Content-Type header or body is handled correctly.

Also, now that the VSCode does a good job of handling large AppMaps, don't set `shallow: true` when generating the default config.

Fixes #175 .

### CODE REVIEW

**Review by dividedmind — COMMENTED** [review]
I don't feel great about pulling in a whole HTTP client as a dependency just to manipulate a URL. If we upgrade apache httpcore, it seems version 5 has URIBuilder class that could be used instead.

**Comment by apotterri** [comment]
I agree that pulling in a whole HTTP client is not great. I did it because we can't use any part of the Apache HttpComponents, because of the way support for HttpAsyncClient works.

I'd hoped that [Shadow's minimization](https://imperceptiblethoughts.com/shadow/configuration/minimizing/) would mean that only a couple of classes from okhttp would get pulled in, but that's not the case.

**Comment by apotterri** [comment]
FWIW, adding okhttp took us a jar file that's 5.8MB to one that's 7.5MB.

**Review by kgilpin — APPROVED** [review]

**Comment by tokazio** [comment]
Still not working, please see https://github.com/getappmap/appmap-java/issues/175

**Pull request merged**
